package vn.ptit.ltm.common.error;

public enum ErrorCode {
    INVALID_REQUEST,
    INVALID_MESSAGE,
    UNAUTHORIZED,
    SESSION_EXPIRED,
    ACCOUNT_ALREADY_LOGGED_IN,
    USERNAME_ALREADY_EXISTS,
    INVALID_CREDENTIALS,

    ROOM_NOT_FOUND,
    ROOM_FULL,
    ALREADY_IN_ROOM,
    NOT_IN_ROOM,
    NOT_ROOM_HOST,
    PLAYER_NOT_IDLE,

    GAME_NOT_STARTED,
    GAME_ALREADY_STARTED,
    NOT_YOUR_TURN,
    INVALID_GAME_STATE,
    INVALID_MOVE,
    NO_VALID_MOVE,
    PIECE_NOT_FOUND,
    PIECE_ALREADY_FINISHED,

    ROLL_NOT_ALLOWED,
    MOVE_NOT_ALLOWED,
    TURN_TIMEOUT,

    SPECTATOR_NOT_ALLOWED,

    INTERNAL_SERVER_ERROR
}
