package vn.ptit.ltm.common.enums;

public enum MessageType {
    REGISTER,
    LOGIN,
    LOGOUT,
    GET_PROFILE,
    PROFILE_RESULT,
    GET_RANKING,
    RANKING_RESULT,
    GET_MATCH_HISTORY,
    MATCH_HISTORY_RESULT,

    GET_ONLINE_PLAYERS,
    ONLINE_PLAYERS_UPDATED,

    CREATE_ROOM,
    JOIN_ROOM,
    LEAVE_ROOM,
    INVITE_PLAYER,
    ACCEPT_INVITE,
    REJECT_INVITE,
    READY,
    UNREADY,
    START_GAME,
    ROOM_UPDATED,

    ROLL_DICE,
    DICE_RESULT,
    MOVE_PIECE,
    MOVE_PIECE_RESULT,
    GAME_STATE,
    GAME_STATE_UPDATED,
    TURN_STARTED,
    TURN_CHANGED,
    TURN_TIMEOUT,
    GAME_OVER,

    CHAT_MESSAGE,

    PING,
    PONG,
    RECONNECT,
    RECONNECT_RESULT,

    ERROR
}
